### ISSUE TITLE
git submodule update / git clone --recursive

### ISSUE THREAD

**Issue by piedup** [gibson042/canonicaljson-go#3]
Hello,

We are using canonicaljson-go for one of our projects. We have automated the deployment of our application using [golang/dep](http://github.com/golang/dep). `dep` uses `git clone --recursive` to fetch the submodules. The .gitmodules file in canonicaljson-go points to `git@github.com:gibson042/canonicaljson-spec.git` so `git clone --recursive`will use ssh to fetch the submodule. Unfortunately that doesn't work when no ssh key has been setup, which is the case for instance in a docker container.

Do you think you could update the .gitmodules so that it points to https://github.com/gibson042/canonicaljson-spec.git instead? This will allow `git clone --recursive` and `git submodule update` to work without using ssh keys.

Thank you for your help.
Pierre

**Comment by gibson042** [comment]
Sure, seems reasonable.

**Comment by piedup** [comment]
Thanks
