### ISSUE TITLE
./decode_test.go:1235:3: Fatal call has possible formatting directive %v

### ISSUE THREAD

**Issue by matrey** [gibson042/canonicaljson-go#4]
When running `go test` I got the following error
`./decode_test.go:1235:3: Fatal call has possible formatting directive %v`

Corresponding code:
`t.Fatal("expected %v == %v", a, b)`

Seems to be enough to use Fatalf instead:
`t.Fatalf("expected %v == %v", a, b)`

**Comment by gibson042** [comment]
Thanks!
